### ISSUE TITLE
The Karazhan

### ISSUE THREAD

**Issue by Motorheadx** [callmephil/SunWellCore#20]
Not work Teator and chess event

**Comment by callmephil** [comment]
Please Read : http://sunwell.pl/#instances

**Comment by Motorheadx** [comment]
I was in the raid 1 minute ago =)

**Comment by Motorheadx** [comment]
do not work these bosses =)

**Comment by lashia** [comment]
Karazhan - available, > not rewritten yet < its not fixed

**Comment by Motorheadx** [comment]
well, you'll be fixed or not?

**Comment by callmephil** [comment]
it's not top priority since xinef & PussyWizard are probably working on that.

**Comment by Motorheadx** [comment]
what is the main priority for 3000 fixed compilation in cmake?=)

**Comment by callmephil** [comment]
I'm mainly alone coding / finding how to fixes issues so you can compile & have a comfortable base to you to work without spending a months on several small issues for all extra it will be on you to work & can decide to share or not your work with us.
I can't spent days or weeks on things that are probably getting fixed by those who shared this core.
